import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.technologies': 'Technologies',
    'nav.process': 'Process',
    'nav.news': 'News',
    'nav.team': 'Team',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',

    // Hero
    'hero.badge': 'Transforming Ideas into Digital Reality',
    'hero.title1': 'We Build the',
    'hero.title2': 'Future',
    'hero.title3': 'of',
    'hero.title4': 'Technology',
    'hero.subtitle': 'ApplKanji delivers scalable, high-quality, and innovative digital solutions that help businesses grow through technology, automation, and smart digital systems.',
    'hero.cta1': 'Start Your Project',
    'hero.cta2': 'Explore Services',
    'hero.stat1.value': '50+',
    'hero.stat1.label': 'Projects Delivered',
    'hero.stat2.value': '30+',
    'hero.stat2.label': 'Happy Clients',
    'hero.stat3.value': '5+',
    'hero.stat3.label': 'Years Experience',
    'hero.stat4.value': '99%',
    'hero.stat4.label': 'Client Satisfaction',
    'hero.scroll': 'Scroll',

    // About
    'about.label': 'About Us',
    'about.title1': 'Driven by',
    'about.title2': 'Innovation',
    'about.subtitle': 'ApplKanji is a modern technology company specializing in delivering scalable, high-quality, and innovative digital solutions for businesses of all sizes.',
    'about.value1.title': 'Mission-Driven',
    'about.value1.desc': 'We focus on delivering measurable results that directly impact your business growth.',
    'about.value2.title': 'Innovation First',
    'about.value2.desc': 'Constantly exploring cutting-edge technologies to provide forward-thinking solutions.',
    'about.value3.title': 'Scalable Solutions',
    'about.value3.desc': 'Building systems designed to grow with your business, from startup to enterprise.',
    'about.value4.title': 'Client Partnership',
    'about.value4.desc': 'We work alongside you as partners, not just vendors, invested in your success.',
    'about.team.label': 'Our Team',
    'about.team.title1': 'Meet the Minds Behind',
    'about.team.title2': 'ApplKanji',
    'about.team.subtitle': 'Our team brings together diverse expertise in software development, architecture, and digital solutions. We\'re passionate about creating technology that makes a difference for our clients and their customers.',
    'about.team.stat1': 'Expert Developers',
    'about.team.stat2': 'Dedication',
    
    // Team roles
    'team.hamza.role': 'Founder & Lead Developer',
    'team.hamza.bio': 'With over 8 years of experience in software development, Hamza founded APPLKANJI with a vision to transform businesses through innovative technology solutions. He specializes in full-stack development and system architecture.',
    'team.hamza.expertise': 'Full-Stack Development, System Architecture, Team Leadership',
    
    'team.ahmad.role': 'Software Architect',
    'team.ahmad.bio': 'Ahmad is a seasoned software architect with expertise in designing scalable and robust systems. He has led the architecture of numerous enterprise-level applications and is passionate about clean code and best practices.',
    'team.ahmad.expertise': 'System Design, Cloud Architecture, Microservices',
    
    'team.maen.role': 'Full-Stack Developer',
    'team.maen.bio': 'Maen is a versatile full-stack developer with a strong background in modern web technologies. He excels at building responsive applications and has contributed to many successful projects.',
    'team.maen.expertise': 'React, Node.js, Database Design, API Development',
    
    'team.belal.role': 'Mobile Developer',
    'team.belal.bio': 'Belal specializes in mobile application development for both iOS and Android platforms. He has a keen eye for user experience and has developed numerous award-winning mobile apps.',
    'team.belal.expertise': 'iOS Development, Android Development, React Native, Flutter',
    
    'team.saif.role': 'Solutions Engineer',
    'team.saif.bio': 'Saif is a solutions engineer who bridges the gap between business requirements and technical implementation. He works closely with clients to understand their needs and deliver tailored solutions.',
    'team.saif.expertise': 'Business Analysis, Solution Design, Client Relations',
    
    'team.ahmadAbuSad.role': 'Cybersecurity Specialist',
    'team.ahmadAbuSad.bio': 'Ahmad Abu Sd is a cybersecurity specialist with extensive experience in protecting digital assets and ensuring information security. He specializes in threat detection, vulnerability assessment, and security architecture.',
    'team.ahmadAbuSad.expertise': 'Cybersecurity, Threat Detection, Security Architecture, Penetration Testing',
    
    'team.mohamad.role': 'RPA Specialist',
    'team.mohamad.bio': 'Mohamad Alnajjar is a Robotic Process Automation (RPA) specialist with expertise in automating business processes and streamlining operations. He designs and implements intelligent automation solutions that reduce manual work and increase efficiency.',
    'team.mohamad.expertise': 'RPA Development, Process Automation, Workflow Optimization, Bot Development, System Integration',
    
    'team.sondos.role': 'AI & Meta VR Specialist',
    'team.sondos.bio': 'Sondos Alqisi is an AI and Meta VR specialist with deep expertise in artificial intelligence, machine learning, and virtual reality technologies. She develops cutting-edge AI solutions and immersive VR experiences that push the boundaries of digital innovation.',
    'team.sondos.expertise': 'Artificial Intelligence, Machine Learning, Meta VR, Virtual Reality, Deep Learning, Computer Vision',
    
    'team.ahmadAshraf.role': 'Full-Stack Developer & Database Expert',
    'team.ahmadAshraf.bio': 'Ahmad Ashraf is a full-stack developer with extensive expertise in database design and .NET frontend development. He specializes in building scalable applications with robust database architectures and modern .NET frameworks.',
    'team.ahmadAshraf.expertise': 'Full-Stack Development, Database Design, .NET Frontend, SQL, Entity Framework, ASP.NET',
    
    'team.mohamadSaber.role': 'Network & Cybersecurity Expert',
    'team.mohamadSaber.bio': 'Mohamad Saber is a network and cybersecurity expert with extensive experience in network infrastructure design, security systems, and cybersecurity protocols. He specializes in securing network environments and implementing robust security measures.',
    'team.mohamadSaber.expertise': 'Network Infrastructure, Cybersecurity, Network Security, Firewall Configuration, Security Protocols, Penetration Testing',
    
    'team.expertise': 'Expertise',
    'team.navigation': 'Team Members',

    // Services
    'services.label': 'Our Services',
    'services.title1': 'What We',
    'services.title2': 'Deliver',
    'services.subtitle': 'From custom software to automation solutions, we provide comprehensive digital services that drive business growth and innovation.',
    'services.intro1': 'We offer comprehensive and innovative digital solutions specifically designed to meet your business needs. From custom software development to advanced mobile applications, we are here to transform your ideas into successful digital reality.',
    'services.intro2': 'We work with you as a strategic partner to understand your deep needs and provide advanced technical solutions that help you grow and thrive in the digital market. Our extensive experience in various technical fields ensures you get the best results.',
    'services.keyPoint1': 'Customized Solutions for Your Needs',
    'services.keyPoint2': 'Modern and Innovative Technologies',
    'services.keyPoint3': 'Professional and Expert Team',
    'services.keyPoint4': 'Continuous Support and Follow-up',
    'services.offeringsTitle': 'What We Offer',
    'services.contactUs': 'Contact Us',
    'services.learnMore': 'Learn more',
    'services.detailTitle': 'Detailed Overview',
    'services.featuresTitle': 'Key Features',
    'services.benefitsTitle': 'Benefits',
    'services.getStarted': 'Get Started',
    
    'services.software.title': 'Custom Software Systems',
    'services.software.desc': 'Tailored software solutions designed specifically for your unique business needs and workflows.',
    'services.software.detail': 'We develop custom software systems that perfectly align with your business processes. Our solutions are built using modern technologies, ensuring scalability, security, and maintainability. From initial concept to deployment and beyond, we provide comprehensive support throughout the entire software lifecycle. Our team works closely with you to understand your unique challenges and deliver solutions that drive real business value. We follow agile methodologies, ensuring rapid iteration and continuous improvement.',
    'services.software.benefits': 'Increase operational efficiency, reduce manual work, improve data accuracy, enhance security, and gain competitive advantage with custom software tailored to your needs.',
    'services.software.b1': 'Increase operational efficiency by up to 60%',
    'services.software.b2': 'Reduce manual work and human errors',
    'services.software.b3': 'Improve data accuracy and consistency',
    'services.software.b4': 'Enhance security with enterprise-grade protection',
    'services.software.b5': 'Gain competitive advantage with unique solutions',
    'services.software.b6': 'Scale seamlessly as your business grows',
    'services.software.f1': 'Enterprise Applications',
    'services.software.f2': 'API Development',
    'services.software.f3': 'System Integration',
    'services.software.f4': 'Database Design & Optimization',
    'services.software.f5': 'Cloud Architecture',
    'services.software.f6': 'Security Implementation',
    'services.software.o1': 'Custom Software Development',
    'services.software.o2': 'Database Design',
    'services.software.o3': 'API Interfaces',
    'services.software.o4': 'System Integration',
    'services.software.o5': 'Comprehensive Testing',
    'services.software.o6': 'Technical Support & Maintenance for 1 Year Free',
    'services.software.o7': '5 Free Changes in the First Year',
    
    'services.web.title': 'Website Development',
    'services.web.desc': 'Professional, responsive websites that establish a strong digital presence for companies and startups.',
    'services.web.detail': 'We create stunning, high-performance websites that not only look great but also convert visitors into customers. Our web solutions are fully responsive, SEO-optimized, and built with the latest technologies to ensure fast loading times and excellent user experience across all devices. We focus on creating intuitive navigation, compelling content, and seamless functionality that engages your audience and drives action. Every website we build is optimized for search engines, mobile devices, and accessibility standards.',
    'services.web.benefits': 'Boost your online presence, attract more customers, improve brand credibility, increase conversions, and stay ahead of competitors with a professionally designed website.',
    'services.web.b1': 'Boost online visibility and brand awareness',
    'services.web.b2': 'Attract and convert more customers',
    'services.web.b3': 'Improve brand credibility and trust',
    'services.web.b4': 'Increase conversion rates by up to 40%',
    'services.web.b5': 'Stay ahead of competitors with modern design',
    'services.web.b6': 'Mobile-first approach for all devices',
    'services.web.f1': 'Corporate Websites',
    'services.web.f2': 'Landing Pages',
    'services.web.f3': 'Web Applications',
    'services.web.f4': 'SEO Optimization',
    'services.web.f5': 'Performance Optimization',
    'services.web.f6': 'Content Management Systems',
    'services.web.o1': 'Professional Website',
    'services.web.o2': 'Domain Name',
    'services.web.o3': 'Hosting',
    'services.web.o4': 'Attractive & Responsive Design',
    'services.web.o5': 'Search Engine Optimization (SEO)',
    'services.web.o6': 'SSL Certificate for Security',
    'services.web.o7': '1 Year Free Technical Support',
    'services.web.o8': '5 Free Changes in the First Year',
    
    'services.ecommerce.title': 'E-commerce Platforms',
    'services.ecommerce.desc': 'Secure and scalable online stores with seamless payment integration and inventory management.',
    'services.ecommerce.detail': 'Build a powerful online store that drives sales and provides an exceptional shopping experience. Our e-commerce solutions include secure payment gateways, comprehensive inventory management, order tracking, customer accounts, and analytics to help you grow your online business. We implement advanced features like product recommendations, wishlists, customer reviews, and multi-currency support. Our platforms are designed to handle high traffic volumes and provide a smooth checkout experience that reduces cart abandonment.',
    'services.ecommerce.benefits': 'Expand your market reach, operate 24/7, reduce overhead costs, track customer behavior, and increase sales with a fully-featured e-commerce platform.',
    'services.ecommerce.b1': 'Expand market reach globally',
    'services.ecommerce.b2': 'Operate 24/7 without physical limitations',
    'services.ecommerce.b3': 'Reduce overhead and operational costs',
    'services.ecommerce.b4': 'Track customer behavior and preferences',
    'services.ecommerce.b5': 'Increase sales with optimized checkout',
    'services.ecommerce.b6': 'Scale to handle peak shopping seasons',
    'services.ecommerce.f1': 'Custom Storefronts',
    'services.ecommerce.f2': 'Payment Integration',
    'services.ecommerce.f3': 'Order Management',
    'services.ecommerce.f4': 'Inventory Management',
    'services.ecommerce.f5': 'Customer Analytics',
    'services.ecommerce.f6': 'Multi-currency Support',
    'services.ecommerce.o1': 'Complete E-commerce Store',
    'services.ecommerce.o2': 'Domain & Hosting',
    'services.ecommerce.o3': 'Secure Payment Gateway',
    'services.ecommerce.o4': 'Inventory Management System',
    'services.ecommerce.o5': 'Product Management Dashboard',
    'services.ecommerce.o6': 'Sales Reports',
    'services.ecommerce.o7': '1 Year Free Technical Support',
    'services.ecommerce.o8': '5 Free Changes in the First Year',
    
    'services.mobile.title': 'Mobile Applications',
    'services.mobile.desc': 'Native iOS and Android apps with modern UI/UX that deliver exceptional user experiences.',
    'services.mobile.detail': 'Transform your business with custom mobile applications that engage users and drive results. We develop native and cross-platform apps with intuitive interfaces, smooth performance, and robust functionality. From concept to App Store deployment, we handle every aspect of mobile app development. Our apps are designed with user experience at the forefront, ensuring intuitive navigation, fast load times, and engaging interactions. We implement push notifications, offline capabilities, and seamless integration with backend systems.',
    'services.mobile.benefits': 'Reach customers on-the-go, improve customer engagement, increase brand visibility, boost sales, and provide convenient access to your services through mobile apps.',
    'services.mobile.b1': 'Reach customers anywhere, anytime',
    'services.mobile.b2': 'Improve customer engagement by 3x',
    'services.mobile.b3': 'Increase brand visibility and recognition',
    'services.mobile.b4': 'Boost sales with in-app purchases',
    'services.mobile.b5': 'Provide convenient 24/7 access',
    'services.mobile.b6': 'Enable push notifications and alerts',
    'services.mobile.f1': 'iOS Development',
    'services.mobile.f2': 'Android Development',
    'services.mobile.f3': 'Cross-Platform',
    'services.mobile.f4': 'UI/UX Design',
    'services.mobile.f5': 'App Store Optimization',
    'services.mobile.f6': 'Push Notifications',
    'services.mobile.o1': 'Android App',
    'services.mobile.o2': 'iOS App',
    'services.mobile.o3': 'User Interface Design',
    'services.mobile.o4': 'Server Integration',
    'services.mobile.o5': 'App Store Publishing',
    'services.mobile.o6': 'Updates & Support',
    'services.mobile.o7': '1 Year Free Technical Support',
    'services.mobile.o8': '5 Free Changes in the First Year',
    
    'services.social.title': 'Social Media Management',
    'services.social.desc': 'Complete digital presence solutions to grow your brand and engage with your audience.',
    'services.social.detail': 'Elevate your brand\'s social media presence with strategic content creation, community engagement, and data-driven insights. We help you build a strong online community, increase brand awareness, and drive meaningful engagement across all major social platforms. Our team creates compelling content, manages your social media accounts, responds to customer inquiries, and analyzes performance metrics to continuously improve your social media strategy. We stay updated with the latest trends and platform updates to keep your brand relevant.',
    'services.social.benefits': 'Build brand awareness, engage with your audience, increase website traffic, generate leads, and strengthen customer relationships through effective social media management.',
    'services.social.b1': 'Build strong brand awareness',
    'services.social.b2': 'Engage with your audience effectively',
    'services.social.b3': 'Increase website traffic by 50%+',
    'services.social.b4': 'Generate qualified leads',
    'services.social.b5': 'Strengthen customer relationships',
    'services.social.b6': 'Monitor and respond to feedback',
    'services.social.f1': 'Content Strategy',
    'services.social.f2': 'Analytics',
    'services.social.f3': 'Community Management',
    'services.social.f4': 'Content Creation',
    'services.social.f5': 'Social Media Advertising',
    'services.social.f6': 'Influencer Partnerships',
    'services.social.o1': 'Social Media Platform',
    'services.social.o2': 'Domain & Hosting',
    'services.social.o3': 'Messaging System',
    'services.social.o4': 'Content Sharing',
    'services.social.o5': 'User Management',
    'services.social.o6': 'Admin Dashboard',
    'services.social.o7': '1 Year Free Technical Support',
    'services.social.o8': '5 Free Changes in the First Year',
    
    'services.rpa.title': 'RPA Solutions',
    'services.rpa.desc': 'Robotic Process Automation to optimize repetitive tasks and streamline business operations.',
    'services.rpa.detail': 'Automate repetitive, rule-based tasks with Robotic Process Automation (RPA) solutions. Our RPA bots work 24/7 to handle data entry, document processing, report generation, and other routine tasks, freeing your team to focus on strategic work that drives business value. We design and deploy intelligent bots that integrate seamlessly with your existing systems, learn from patterns, and adapt to changes. Our RPA solutions are scalable, secure, and provide detailed analytics on automation performance.',
    'services.rpa.benefits': 'Reduce operational costs, eliminate human errors, increase processing speed, improve compliance, and scale operations without additional headcount.',
    'services.rpa.b1': 'Reduce operational costs by up to 70%',
    'services.rpa.b2': 'Eliminate human errors completely',
    'services.rpa.b3': 'Increase processing speed by 10x',
    'services.rpa.b4': 'Improve compliance and accuracy',
    'services.rpa.b5': 'Scale operations without hiring',
    'services.rpa.b6': 'Free up team for strategic work',
    'services.rpa.f1': 'Process Automation',
    'services.rpa.f2': 'Data Extraction',
    'services.rpa.f3': 'Workflow Bots',
    'services.rpa.f4': 'Document Processing',
    'services.rpa.f5': 'Report Generation',
    'services.rpa.f6': 'System Integration',
    'services.rpa.o1': 'Automation Robots',
    'services.rpa.o2': 'System Integration',
    'services.rpa.o3': 'Automated Workflows',
    'services.rpa.o4': 'Reports & Monitoring Tools',
    'services.rpa.o5': 'Maintenance & Updates',
    'services.rpa.o6': 'Team Training',
    'services.rpa.o7': '1 Year Free Technical Support',
    'services.rpa.o8': '5 Free Changes in the First Year',
    
    'services.automation.title': 'Business Automation',
    'services.automation.desc': 'Internal tools and systems that automate processes and boost operational efficiency.',
    'services.automation.detail': 'Streamline your business operations with custom automation solutions. We build internal tools, dashboards, and systems that automate workflows, improve data visibility, and enhance decision-making. From CRM integration to automated reporting, we help you work smarter, not harder. Our automation solutions connect disparate systems, trigger actions based on events, and provide real-time insights into your business operations. We ensure seamless integration with your existing tools and provide comprehensive training for your team.',
    'services.automation.benefits': 'Improve productivity, reduce manual work, enhance data accuracy, enable better decision-making, and optimize resource allocation with business automation.',
    'services.automation.b1': 'Improve productivity by 50%+',
    'services.automation.b2': 'Reduce manual work significantly',
    'services.automation.b3': 'Enhance data accuracy and consistency',
    'services.automation.b4': 'Enable data-driven decision-making',
    'services.automation.b5': 'Optimize resource allocation',
    'services.automation.b6': 'Real-time insights and reporting',
    'services.automation.f1': 'Custom Dashboards',
    'services.automation.f2': 'Reporting Tools',
    'services.automation.f3': 'CRM Systems',
    'services.automation.f4': 'Workflow Automation',
    'services.automation.f5': 'Data Integration',
    'services.automation.f6': 'Business Intelligence',
    'services.automation.o1': 'Complete Automation Systems',
    'services.automation.o2': 'Application Integration',
    'services.automation.o3': 'Smart Workflows',
    'services.automation.o4': 'Automated Reports',
    'services.automation.o5': 'Monitoring & Tracking',
    'services.automation.o6': 'Continuous Technical Support',
    'services.automation.o7': '1 Year Free Technical Support',
    'services.automation.o8': '5 Free Changes in the First Year',
    
    'services.workflow.title': 'Workflow Automation',
    'services.workflow.desc': 'Advanced workflow automation using n8n, implemented cleanly, scalably, and professionally.',
    'services.workflow.detail': 'Connect your tools and automate complex workflows with n8n-powered solutions. We design and implement sophisticated automation workflows that integrate multiple systems, trigger actions based on events, and orchestrate complex business processes seamlessly. Our n8n implementations are built with best practices, ensuring reliability, scalability, and maintainability. We create custom nodes when needed, optimize workflow performance, and provide comprehensive documentation for your team.',
    'services.workflow.benefits': 'Connect disparate systems, automate complex workflows, reduce manual intervention, improve process reliability, and accelerate business operations.',
    'services.workflow.b1': 'Connect disparate systems seamlessly',
    'services.workflow.b2': 'Automate complex multi-step workflows',
    'services.workflow.b3': 'Reduce manual intervention by 80%',
    'services.workflow.b4': 'Improve process reliability and consistency',
    'services.workflow.b5': 'Accelerate business operations',
    'services.workflow.b6': 'Enable real-time data synchronization',
    'services.workflow.f1': 'n8n Integration',
    'services.workflow.f2': 'API Orchestration',
    'services.workflow.f3': 'Event-Driven Flows',
    'services.workflow.f4': 'Custom Node Development',
    'services.workflow.f5': 'Workflow Optimization',
    'services.workflow.f6': 'Monitoring & Analytics',
    'services.workflow.o1': 'Workflow Management',
    'services.workflow.o2': 'System Integration',
    'services.workflow.o3': 'Reports & Analytics',
    'services.workflow.o4': 'Automated Notifications',
    'services.workflow.o5': 'Comprehensive Dashboard',
    'services.workflow.o6': 'Training & Follow-up',
    'services.workflow.o7': '1 Year Free Technical Support',
    'services.workflow.o8': '5 Free Changes in the First Year',

    // Technologies
    'tech.label': 'Technologies',
    'tech.title1': 'Our Tech',
    'tech.title2': 'Stack',
    'tech.subtitle': 'We leverage the latest technologies and tools to build robust, scalable, and future-proof solutions.',
    'tech.cta': 'Don\'t see what you need? We\'re always exploring new technologies.',
    'tech.ctaLink': 'Let\'s discuss your requirements →',
    'tech.frontend': 'Frontend',
    'tech.backend': 'Backend',
    'tech.mobile': 'Mobile',
    'tech.cloud': 'Cloud & DevOps',
    'tech.automation': 'Automation',
    'tech.tools': 'Tools',

    // Process
    'process.label': 'Our Process',
    'process.title1': 'How We',
    'process.title2': 'Work',
    'process.subtitle': 'A proven methodology that ensures quality, transparency, and successful delivery of every project.',
    'process.step1.title': 'Discovery',
    'process.step1.desc': 'We start by understanding your business, goals, and challenges through in-depth consultation.',
    'process.step2.title': 'Research & Analysis',
    'process.step2.desc': 'We analyze your market, competitors, and users to inform our strategic approach.',
    'process.step3.title': 'Design & Planning',
    'process.step3.desc': 'Creating wireframes, prototypes, and detailed technical specifications for your solution.',
    'process.step4.title': 'Development',
    'process.step4.desc': 'Agile development with regular updates, testing, and iterations based on your feedback.',
    'process.step5.title': 'Launch',
    'process.step5.desc': 'Thorough testing, optimization, and seamless deployment of your solution.',
    'process.step6.title': 'Support & Growth',
    'process.step6.desc': 'Ongoing maintenance, updates, and strategic guidance to help your business grow.',

    // Contact
    'contact.label': 'Get In Touch',
    'contact.title1': 'Let\'s Build',
    'contact.title2': 'Together',
    'contact.subtitle': 'Ready to start your next project? We\'d love to hear from you. Get in touch and let\'s create something amazing.',
    'contact.form.name': 'Your Name',
    'contact.form.namePlaceholder': 'John Doe',
    'contact.form.email': 'Email Address',
    'contact.form.emailPlaceholder': 'john@company.com',
    'contact.form.company': 'Company (Optional)',
    'contact.form.companyPlaceholder': 'Your Company Name',
    'contact.form.message': 'Your Message',
    'contact.form.messagePlaceholder': 'Tell us about your project...',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.info.locationValue': 'Remote Team, Worldwide',
    'contact.follow': 'Follow Us',
    'contact.response': 'Quick Response Guaranteed',
    'contact.responseDesc': 'We typically respond within 24 hours',
    'contact.toast.title': 'Message sent!',
    'contact.toast.desc': 'We\'ll get back to you within 24 hours.',

    // News
    'news.label': 'Latest News',
    'news.title1': 'Stay Updated',
    'news.title2': 'With Our News',
    'news.subtitle': 'Follow our journey as we attend conferences, participate in events, and share important updates about our company and industry insights.',
    'news.readMore': 'Read More',
    'news.viewAll': 'View All News',
    'news.allNews': 'All News & Updates',
    'news.allNewsDesc': 'Explore all our latest updates, events, and achievements',
    'news.category.conference': 'Conference',
    'news.category.event': 'Event',
    'news.category.update': 'Update',
    'news.category.award': 'Award',
    'news.dateFormat': 'MMM dd, yyyy',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.description': 'APPLKANJI delivers scalable, high-quality, and innovative digital solutions that help businesses grow through technology, automation, and smart digital systems.',
    'footer.quickLinks': 'Quick Links',
    'footer.contactInfo': 'Contact Information',
    'footer.followUs': 'Follow Us',
    'footer.socialDesc': 'Stay connected with us on social media',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
  },
  ar: {
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'خدماتنا',
    'nav.technologies': 'التقنيات',
    'nav.process': 'منهجيتنا',
    'nav.news': 'الأخبار',
    'nav.team': 'فريقنا',
    'nav.contact': 'تواصل معنا',
    'nav.getStarted': 'ابدأ الآن',

    // Hero
    'hero.badge': 'نحوّل الأفكار إلى واقع رقمي',
    'hero.title1': 'نحوّل',
    'hero.title2': 'أفكارك',
    'hero.title3': 'إلى',
    'hero.title4': 'واقع رقمي',
    'hero.subtitle': 'APPLKANJI تقدم حلولاً رقمية مبتكرة وقابلة للتطوير تساعد الشركات على النمو من خلال التكنولوجيا والأتمتة والأنظمة الرقمية الذكية.',
    'hero.cta1': 'ابدأ مشروعك',
    'hero.cta2': 'استكشف خدماتنا',
    'hero.stat1.value': '+50',
    'hero.stat1.label': 'مشروع منجز',
    'hero.stat2.value': '+30',
    'hero.stat2.label': 'عميل سعيد',
    'hero.stat3.value': '+5',
    'hero.stat3.label': 'سنوات خبرة',
    'hero.stat4.value': '99%',
    'hero.stat4.label': 'رضا العملاء',
    'hero.scroll': 'اسحب للأسفل',

    // About
    'about.label': 'من نحن',
    'about.title1': 'مدفوعون',
    'about.title2': 'بالابتكار',
    'about.subtitle': 'APPLKANJI شركة تكنولوجيا حديثة متخصصة في تقديم حلول رقمية مبتكرة وعالية الجودة وقابلة للتطوير للشركات من جميع الأحجام.',
    'about.value1.title': 'موجهون بالمهمة',
    'about.value1.desc': 'نركز على تقديم نتائج قابلة للقياس تؤثر مباشرة على نمو أعمالك.',
    'about.value2.title': 'الابتكار أولاً',
    'about.value2.desc': 'نستكشف باستمرار أحدث التقنيات لتقديم حلول مستقبلية.',
    'about.value3.title': 'حلول قابلة للتطوير',
    'about.value3.desc': 'نبني أنظمة مصممة للنمو مع عملك، من شركة ناشئة إلى مؤسسة كبرى.',
    'about.value4.title': 'شراكة مع العملاء',
    'about.value4.desc': 'نعمل معك كشركاء، لا مجرد موردين، مستثمرين في نجاحك.',
    'about.team.label': 'فريقنا',
    'about.team.title1': 'تعرف على العقول خلف',
    'about.team.title2': 'APPLKANJI',
    'about.team.subtitle': 'يجمع فريقنا خبرات متنوعة في تطوير البرمجيات والهندسة المعمارية والحلول الرقمية. نحن متحمسون لإنشاء تكنولوجيا تحدث فرقاً لعملائنا.',
    'about.team.stat1': 'مطورين خبراء',
    'about.team.stat2': 'تفاني كامل',
    
    // Team roles
    'team.hamza.role': 'المؤسس والمطور الرئيسي',
    'team.hamza.bio': 'مع أكثر من 8 سنوات من الخبرة في تطوير البرمجيات، أسس حمزة APPLKANJI برؤية لتحويل الأعمال من خلال حلول تكنولوجية مبتكرة. يتخصص في التطوير الشامل وهندسة الأنظمة.',
    'team.hamza.expertise': 'التطوير الشامل، هندسة الأنظمة، قيادة الفريق',
    
    'team.ahmad.role': 'مهندس البرمجيات',
    'team.ahmad.bio': 'أحمد مهندس برمجيات محترف متخصص في تصميم أنظمة قابلة للتطوير وقوية. قاد هندسة العديد من التطبيقات على مستوى المؤسسات وهو شغوف بالكود النظيف وأفضل الممارسات.',
    'team.ahmad.expertise': 'تصميم الأنظمة، هندسة السحابة، الخدمات الصغيرة',
    
    'team.maen.role': 'مطور Full-Stack',
    'team.maen.bio': 'معين مطور شامل متعدد الاستخدامات بخلفية قوية في تقنيات الويب الحديثة. يتفوق في بناء التطبيقات المتجاوبة وساهم في العديد من المشاريع الناجحة.',
    'team.maen.expertise': 'React، Node.js، تصميم قواعد البيانات، تطوير API',
    
    'team.belal.role': 'مطور تطبيقات الموبايل',
    'team.belal.bio': 'بلال متخصص في تطوير تطبيقات الموبايل لمنصتي iOS و Android. لديه عين حادة لتجربة المستخدم وطور العديد من التطبيقات المحمولة الحائزة على جوائز.',
    'team.belal.expertise': 'تطوير iOS، تطوير Android، React Native، Flutter',
    
    'team.saif.role': 'مهندس الحلول',
    'team.saif.bio': 'سيف مهندس حلول يربط بين متطلبات الأعمال والتنفيذ التقني. يعمل بشكل وثيق مع العملاء لفهم احتياجاتهم وتقديم حلول مخصصة.',
    'team.saif.expertise': 'تحليل الأعمال، تصميم الحلول، علاقات العملاء',
    
    'team.ahmadAbuSad.role': 'أخصائي الأمن السيبراني',
    'team.ahmadAbuSad.bio': 'أحمد أبو صد أخصائي أمن سيبراني بخبرة واسعة في حماية الأصول الرقمية وضمان أمان المعلومات. يتخصص في اكتشاف التهديدات وتقييم الثغرات وهندسة الأمان.',
    'team.ahmadAbuSad.expertise': 'الأمن السيبراني، اكتشاف التهديدات، هندسة الأمان، اختبار الاختراق',
    
    'team.mohamad.role': 'أخصائي RPA',
    'team.mohamad.bio': 'محمد النجار أخصائي أتمتة العمليات الروبوتية (RPA) بخبرة في أتمتة عمليات الأعمال وتبسيط العمليات. يصمم وينفذ حلول أتمتة ذكية تقلل من العمل اليدوي وتزيد الكفاءة.',
    'team.mohamad.expertise': 'تطوير RPA، أتمتة العمليات، تحسين سير العمل، تطوير الروبوتات، تكامل الأنظمة',
    
    'team.sondos.role': 'أخصائية ذكاء اصطناعي و Meta VR',
    'team.sondos.bio': 'سندس القيسي أخصائية في الذكاء الاصطناعي و Meta VR بخبرة عميقة في الذكاء الاصطناعي وتعلم الآلة وتقنيات الواقع الافتراضي. تطور حلول ذكاء اصطناعي متطورة وتجارب VR غامرة تدفع حدود الابتكار الرقمي.',
    'team.sondos.expertise': 'الذكاء الاصطناعي، تعلم الآلة، Meta VR، الواقع الافتراضي، التعلم العميق، رؤية الحاسوب',
    
    'team.ahmadAshraf.role': 'مطور Full-Stack وخبير قواعد البيانات',
    'team.ahmadAshraf.bio': 'أحمد أشرف مطور Full-Stack بخبرة واسعة في تصميم قواعد البيانات وتطوير الواجهات الأمامية باستخدام .NET. يتخصص في بناء تطبيقات قابلة للتطوير بهندسة قواعد بيانات قوية وإطارات عمل .NET الحديثة.',
    'team.ahmadAshraf.expertise': 'التطوير الشامل، تصميم قواعد البيانات، .NET Frontend، SQL، Entity Framework، ASP.NET',
    
    'team.mohamadSaber.role': 'خبير الشبكات والأمن السيبراني',
    'team.mohamadSaber.bio': 'محمد صابر خبير في الشبكات والأمن السيبراني بخبرة واسعة في تصميم البنية التحتية للشبكات وأنظمة الأمان وبروتوكولات الأمن السيبراني. يتخصص في تأمين بيئات الشبكات وتنفيذ إجراءات أمنية قوية.',
    'team.mohamadSaber.expertise': 'البنية التحتية للشبكات، الأمن السيبراني، أمان الشبكات، تكوين الجدران النارية، بروتوكولات الأمان، اختبار الاختراق',
    
    'team.expertise': 'الخبرات',
    'team.navigation': 'أعضاء الفريق',

    // Services
    'services.label': 'خدماتنا',
    'services.title1': 'ما',
    'services.title2': 'نقدمه',
    'services.subtitle': 'من البرمجيات المخصصة إلى حلول الأتمتة، نقدم خدمات رقمية شاملة تدفع نمو الأعمال والابتكار.',
    'services.keyPoint1': 'حلول مخصصة لاحتياجاتك',
    'services.keyPoint2': 'تقنيات حديثة ومبتكرة',
    'services.keyPoint3': 'فريق محترف وخبير',
    'services.keyPoint4': 'دعم مستمر ومتابعة',
    'services.offeringsTitle': 'ما يتم تقديمه',
    'services.contactUs': 'تواصل معنا',
    'services.intro1': 'نقدم حلولاً رقمية شاملة ومبتكرة مصممة خصيصاً لتلبية احتياجات عملك. من تطوير البرمجيات المخصصة إلى تطبيقات الموبايل المتقدمة، نحن هنا لتحويل أفكارك إلى واقع رقمي ناجح.',
    'services.intro2': 'نعمل معك كشريك استراتيجي لفهم احتياجاتك العميقة وتقديم حلول تقنية متقدمة تساعدك على النمو والازدهار في السوق الرقمي. خبرتنا الواسعة في مختلف المجالات التقنية تضمن لك الحصول على أفضل النتائج.',
    'services.learnMore': 'اعرف المزيد',
    'services.detailTitle': 'نظرة عامة تفصيلية',
    'services.featuresTitle': 'الميزات الرئيسية',
    'services.benefitsTitle': 'الفوائد',
    'services.getStarted': 'ابدأ الآن',
    'services.detailTitle': 'نظرة عامة تفصيلية',
    'services.featuresTitle': 'الميزات الرئيسية',
    'services.benefitsTitle': 'الفوائد',
    'services.getStarted': 'ابدأ الآن',
    
    'services.software.title': 'أنظمة برمجية مخصصة',
    'services.software.desc': 'حلول برمجية مصممة خصيصاً لاحتياجات عملك الفريدة وسير العمل.',
    'services.software.detail': 'نطور أنظمة برمجية مخصصة تتماشى تماماً مع عمليات عملك. حلولنا مبنية باستخدام أحدث التقنيات، مما يضمن قابلية التوسع والأمان وسهولة الصيانة. من المفهوم الأولي إلى النشر وما بعده، نقدم دعماً شاملاً طوال دورة حياة البرنامج بالكامل. يعمل فريقنا بشكل وثيق معك لفهم تحدياتك الفريدة وتقديم حلول تدفع قيمة الأعمال الحقيقية. نتبع منهجيات Agile، مما يضمن التكرار السريع والتحسين المستمر.',
    'services.software.benefits': 'زيادة الكفاءة التشغيلية، تقليل العمل اليدوي، تحسين دقة البيانات، تعزيز الأمان، واكتساب ميزة تنافسية مع برمجيات مخصصة تلبي احتياجاتك.',
    'services.software.b1': 'زيادة الكفاءة التشغيلية بنسبة تصل إلى 60%',
    'services.software.b2': 'تقليل العمل اليدوي والأخطاء البشرية',
    'services.software.b3': 'تحسين دقة البيانات والاتساق',
    'services.software.b4': 'تعزيز الأمان بحماية على مستوى المؤسسات',
    'services.software.b5': 'اكتساب ميزة تنافسية مع حلول فريدة',
    'services.software.b6': 'التوسع بسلاسة مع نمو عملك',
    'services.software.f1': 'تطبيقات المؤسسات',
    'services.software.f2': 'تطوير الـ API',
    'services.software.f3': 'تكامل الأنظمة',
    'services.software.f4': 'تصميم وتحسين قواعد البيانات',
    'services.software.f5': 'هندسة السحابة',
    'services.software.f6': 'تنفيذ الأمان',
    'services.software.o1': 'تطوير البرمجيات المخصصة',
    'services.software.o2': 'تصميم قاعدة البيانات',
    'services.software.o3': 'واجهات برمجية (API)',
    'services.software.o4': 'تكامل الأنظمة',
    'services.software.o5': 'اختبارات شاملة',
    'services.software.o6': 'دعم فني وصيانة لمدة سنة مجاناً',
    'services.software.o7': '5 تغييرات مجانية خلال السنة الأولى',
    
    'services.web.title': 'تطوير المواقع',
    'services.web.desc': 'مواقع احترافية ومتجاوبة تؤسس حضوراً رقمياً قوياً للشركات.',
    'services.web.detail': 'ننشئ مواقع ويب مذهلة وعالية الأداء لا تبدو رائعة فحسب، بل تحول الزوار إلى عملاء أيضاً. حلولنا الويب متجاوبة بالكامل، محسّنة لمحركات البحث، ومبنية بأحدث التقنيات لضمان أوقات تحميل سريعة وتجربة مستخدم ممتازة عبر جميع الأجهزة. نركز على إنشاء تنقل بديهي ومحتوى مقنع ووظائف سلسة تجذب جمهورك وتدفعهم للعمل. كل موقع نبنيه محسّن لمحركات البحث والأجهزة المحمولة ومعايير إمكانية الوصول.',
    'services.web.benefits': 'عزز حضورك على الإنترنت، اجذب المزيد من العملاء، حسّن مصداقية علامتك التجارية، زد التحويلات، وتقدم على المنافسين بموقع ويب مصمم بشكل احترافي.',
    'services.web.b1': 'تعزيز الرؤية عبر الإنترنت والوعي بالعلامة التجارية',
    'services.web.b2': 'جذب وتحويل المزيد من العملاء',
    'services.web.b3': 'تحسين مصداقية وثقة العلامة التجارية',
    'services.web.b4': 'زيادة معدلات التحويل بنسبة تصل إلى 40%',
    'services.web.b5': 'التقدم على المنافسين بتصميم حديث',
    'services.web.b6': 'نهج Mobile-First لجميع الأجهزة',
    'services.web.f1': 'مواقع الشركات',
    'services.web.f2': 'صفحات الهبوط',
    'services.web.f3': 'تطبيقات الويب',
    'services.web.f4': 'تحسين محركات البحث',
    'services.web.f5': 'تحسين الأداء',
    'services.web.f6': 'أنظمة إدارة المحتوى',
    'services.web.o1': 'موقع ويب احترافي',
    'services.web.o2': 'دومين (اسم نطاق)',
    'services.web.o3': 'استضافة (Hosting)',
    'services.web.o4': 'تصميم جذاب ومتجاوب',
    'services.web.o5': 'محرك بحث (SEO)',
    'services.web.o6': 'شهادة SSL للأمان',
    'services.web.o7': 'دعم فني لمدة سنة مجاناً',
    'services.web.o8': '5 تغييرات مجانية خلال السنة الأولى',
    
    'services.ecommerce.title': 'منصات التجارة الإلكترونية',
    'services.ecommerce.desc': 'متاجر إلكترونية آمنة وقابلة للتطوير مع تكامل سلس للدفع وإدارة المخزون.',
    'services.ecommerce.detail': 'أنشئ متجراً إلكترونياً قوياً يدفع المبيعات ويوفر تجربة تسوق استثنائية. تشمل حلول التجارة الإلكترونية لدينا بوابات دفع آمنة وإدارة شاملة للمخزون وتتبع الطلبات وحسابات العملاء والتحليلات لمساعدتك على نمو عملك عبر الإنترنت. ننفذ ميزات متقدمة مثل توصيات المنتجات وقوائم الأمنيات ومراجعات العملاء والدعم متعدد العملات. تم تصميم منصاتنا للتعامل مع أحجام حركة مرور عالية وتوفير تجربة دفع سلسة تقلل من التخلي عن عربة التسوق.',
    'services.ecommerce.b1': 'توسيع الوصول إلى السوق عالمياً',
    'services.ecommerce.b2': 'التشغيل على مدار الساعة دون قيود مادية',
    'services.ecommerce.b3': 'تقليل التكاليف العامة والتشغيلية',
    'services.ecommerce.b4': 'تتبع سلوك وتفضيلات العملاء',
    'services.ecommerce.b5': 'زيادة المبيعات مع دفع محسّن',
    'services.ecommerce.b6': 'التوسع للتعامل مع مواسم التسوق الذروة',
    'services.ecommerce.f1': 'واجهات متاجر مخصصة',
    'services.ecommerce.f2': 'تكامل الدفع',
    'services.ecommerce.f3': 'إدارة الطلبات',
    'services.ecommerce.f4': 'إدارة المخزون',
    'services.ecommerce.f5': 'تحليلات العملاء',
    'services.ecommerce.f6': 'دعم متعدد العملات',
    'services.ecommerce.o1': 'متجر إلكتروني كامل',
    'services.ecommerce.o2': 'دومين واستضافة',
    'services.ecommerce.o3': 'بوابة دفع آمنة',
    'services.ecommerce.o4': 'نظام إدارة المخزون',
    'services.ecommerce.o5': 'لوحة تحكم للمنتجات',
    'services.ecommerce.o6': 'تقارير المبيعات',
    'services.ecommerce.o7': 'دعم فني لمدة سنة مجاناً',
    'services.ecommerce.o8': '5 تغييرات مجانية خلال السنة الأولى',
    
    'services.mobile.title': 'تطبيقات الموبايل',
    'services.mobile.desc': 'تطبيقات iOS و Android بتصميم حديث تقدم تجارب مستخدم استثنائية.',
    'services.mobile.detail': 'حوّل عملك مع تطبيقات الموبايل المخصصة التي تجذب المستخدمين وتدفع النتائج. نطور تطبيقات أصلية وعبر المنصات بواجهات بديهية وأداء سلس ووظائف قوية. من المفهوم إلى نشر متجر التطبيقات، نتعامل مع كل جانب من جوانب تطوير تطبيقات الموبايل. تم تصميم تطبيقاتنا مع تجربة المستخدم في المقدمة، مما يضمن التنقل البديهي وأوقات التحميل السريعة والتفاعلات الجذابة. ننفذ الإشعارات الفورية وإمكانيات العمل دون اتصال والتكامل السلس مع أنظمة الخلفية.',
    'services.mobile.b1': 'الوصول إلى العملاء في أي مكان وفي أي وقت',
    'services.mobile.b2': 'تحسين تفاعل العملاء بمقدار 3 أضعاف',
    'services.mobile.b3': 'زيادة الرؤية والاعتراف بالعلامة التجارية',
    'services.mobile.b4': 'زيادة المبيعات مع المشتريات داخل التطبيق',
    'services.mobile.b5': 'توفير وصول مريح على مدار الساعة',
    'services.mobile.b6': 'تمكين الإشعارات الفورية والتنبيهات',
    'services.mobile.f1': 'تطوير iOS',
    'services.mobile.f2': 'تطوير Android',
    'services.mobile.f3': 'عبر المنصات',
    'services.mobile.f4': 'تصميم UI/UX',
    'services.mobile.f5': 'تحسين متجر التطبيقات',
    'services.mobile.f6': 'الإشعارات الفورية',
    'services.mobile.o1': 'تطبيق Android',
    'services.mobile.o2': 'تطبيق iOS',
    'services.mobile.o3': 'تصميم واجهات مستخدم',
    'services.mobile.o4': 'ربط مع الخوادم',
    'services.mobile.o5': 'نشر على المتاجر',
    'services.mobile.o6': 'تحديثات ودعم',
    'services.mobile.o7': 'دعم فني لمدة سنة مجاناً',
    'services.mobile.o8': '5 تغييرات مجانية خلال السنة الأولى',
    
    'services.social.title': 'إدارة وسائل التواصل',
    'services.social.desc': 'حلول حضور رقمي كاملة لتنمية علامتك التجارية والتفاعل مع جمهورك.',
    'services.social.detail': 'ارفع حضور علامتك التجارية على وسائل التواصل الاجتماعي مع إنشاء محتوى استراتيجي وتفاعل المجتمع ورؤى مدفوعة بالبيانات. نساعدك على بناء مجتمع قوي عبر الإنترنت وزيادة الوعي بالعلامة التجارية ودفع التفاعل الهادف عبر جميع منصات التواصل الاجتماعي الرئيسية. ينشئ فريقنا محتوى مقنعاً ويدير حسابات وسائل التواصل الاجتماعي الخاصة بك ويستجيب لاستفسارات العملاء ويحلل مقاييس الأداء لتحسين استراتيجية وسائل التواصل الاجتماعي الخاصة بك باستمرار. نبقى محدثين بأحدث الاتجاهات وتحديثات المنصة لإبقاء علامتك التجارية ذات صلة.',
    'services.social.b1': 'بناء وعي قوي بالعلامة التجارية',
    'services.social.b2': 'التفاعل مع جمهورك بفعالية',
    'services.social.b3': 'زيادة حركة مرور الموقع بنسبة 50%+',
    'services.social.b4': 'توليد عملاء محتملين مؤهلين',
    'services.social.b5': 'تعزيز علاقات العملاء',
    'services.social.b6': 'مراقبة والاستجابة للتعليقات',
    'services.social.f1': 'استراتيجية المحتوى',
    'services.social.f2': 'التحليلات',
    'services.social.f3': 'إدارة المجتمع',
    'services.social.f4': 'إنشاء المحتوى',
    'services.social.f5': 'إعلانات وسائل التواصل',
    'services.social.f6': 'شراكات المؤثرين',
    'services.social.o1': 'منصة تواصل اجتماعي',
    'services.social.o2': 'دومين واستضافة',
    'services.social.o3': 'نظام الرسائل',
    'services.social.o4': 'مشاركة المحتوى',
    'services.social.o5': 'إدارة المستخدمين',
    'services.social.o6': 'لوحة تحكم إدارية',
    'services.social.o7': 'دعم فني لمدة سنة مجاناً',
    'services.social.o8': '5 تغييرات مجانية خلال السنة الأولى',
    
    'services.rpa.title': 'حلول RPA',
    'services.rpa.desc': 'أتمتة العمليات الروبوتية لتحسين المهام المتكررة وتبسيط العمليات.',
    'services.rpa.detail': 'أتمت المهام المتكررة القائمة على القواعد مع حلول أتمتة العمليات الروبوتية (RPA). تعمل روبوتات RPA لدينا على مدار الساعة للتعامل مع إدخال البيانات ومعالجة المستندات وإنشاء التقارير والمهام الروتينية الأخرى، مما يحرر فريقك للتركيز على العمل الاستراتيجي الذي يدفع قيمة الأعمال. نصمم وننشر روبوتات ذكية تتكامل بسلاسة مع أنظمتك الحالية وتتعلم من الأنماط وتتكيف مع التغييرات. حلول RPA لدينا قابلة للتطوير وآمنة وتوفر تحليلات مفصلة حول أداء الأتمتة.',
    'services.rpa.b1': 'تقليل التكاليف التشغيلية بنسبة تصل إلى 70%',
    'services.rpa.b2': 'القضاء على الأخطاء البشرية تماماً',
    'services.rpa.b3': 'زيادة سرعة المعالجة بمقدار 10 أضعاف',
    'services.rpa.b4': 'تحسين الامتثال والدقة',
    'services.rpa.b5': 'توسيع العمليات دون توظيف',
    'services.rpa.b6': 'تحرير الفريق للعمل الاستراتيجي',
    'services.rpa.f1': 'أتمتة العمليات',
    'services.rpa.f2': 'استخراج البيانات',
    'services.rpa.f3': 'روبوتات سير العمل',
    'services.rpa.f4': 'معالجة المستندات',
    'services.rpa.f5': 'إنشاء التقارير',
    'services.rpa.f6': 'تكامل الأنظمة',
    'services.rpa.o1': 'روبوتات أتمتة',
    'services.rpa.o2': 'تكامل مع الأنظمة',
    'services.rpa.o3': 'سير عمل تلقائي',
    'services.rpa.o4': 'تقارير وأدوات مراقبة',
    'services.rpa.o5': 'صيانة وتحديثات',
    'services.rpa.o6': 'تدريب الفريق',
    'services.rpa.o7': 'دعم فني لمدة سنة مجاناً',
    'services.rpa.o8': '5 تغييرات مجانية خلال السنة الأولى',
    
    'services.automation.title': 'أتمتة الأعمال',
    'services.automation.desc': 'أدوات وأنظمة داخلية تؤتمت العمليات وتعزز الكفاءة التشغيلية.',
    'services.automation.detail': 'بسّط عمليات عملك مع حلول الأتمتة المخصصة. نبني أدوات داخلية ولوحات تحكم وأنظمة تؤتمت سير العمل وتحسن رؤية البيانات وتعزز اتخاذ القرار. من تكامل CRM إلى التقارير المؤتمتة، نساعدك على العمل بذكاء أكبر وليس بجهد أكبر. تربط حلول الأتمتة لدينا بين الأنظمة المختلفة وتطلق الإجراءات بناءً على الأحداث وتوفر رؤى فورية في عمليات عملك. نضمن التكامل السلس مع أدواتك الحالية ونوفر تدريباً شاملاً لفريقك.',
    'services.automation.b1': 'تحسين الإنتاجية بنسبة 50%+',
    'services.automation.b2': 'تقليل العمل اليدوي بشكل كبير',
    'services.automation.b3': 'تعزيز دقة واتساق البيانات',
    'services.automation.b4': 'تمكين اتخاذ القرارات القائمة على البيانات',
    'services.automation.b5': 'تحسين تخصيص الموارد',
    'services.automation.b6': 'رؤى وتقارير فورية',
    'services.automation.f1': 'لوحات تحكم مخصصة',
    'services.automation.f2': 'أدوات التقارير',
    'services.automation.f3': 'أنظمة CRM',
    'services.automation.f4': 'أتمتة سير العمل',
    'services.automation.f5': 'تكامل البيانات',
    'services.automation.f6': 'ذكاء الأعمال',
    'services.automation.o1': 'أنظمة أتمتة كاملة',
    'services.automation.o2': 'تكامل مع التطبيقات',
    'services.automation.o3': 'سير عمل ذكي',
    'services.automation.o4': 'تقارير تلقائية',
    'services.automation.o5': 'مراقبة ومتابعة',
    'services.automation.o6': 'دعم فني مستمر',
    'services.automation.o7': 'دعم فني لمدة سنة مجاناً',
    'services.automation.o8': '5 تغييرات مجانية خلال السنة الأولى',
    
    'services.workflow.title': 'أتمتة سير العمل',
    'services.workflow.desc': 'أتمتة سير عمل متقدمة باستخدام n8n، منفذة بشكل نظيف وقابل للتطوير.',
    'services.workflow.detail': 'اربط أدواتك وأتمت سير العمل المعقدة مع حلول مدعومة بـ n8n. نصمم وننفذ سير عمل أتمتة متطورة تدمج أنظمة متعددة وتطلق الإجراءات بناءً على الأحداث وتنسق عمليات الأعمال المعقدة بسلاسة. تنفيذات n8n لدينا مبنية بأفضل الممارسات، مما يضمن الموثوقية والقابلية للتطوير وسهولة الصيانة. ننشئ عقداً مخصصة عند الحاجة ونحسّن أداء سير العمل ونوفر وثائق شاملة لفريقك.',
    'services.workflow.b1': 'ربط الأنظمة المختلفة بسلاسة',
    'services.workflow.b2': 'أتمتة سير العمل متعددة الخطوات المعقدة',
    'services.workflow.b3': 'تقليل التدخل اليدوي بنسبة 80%',
    'services.workflow.b4': 'تحسين موثوقية واتساق العمليات',
    'services.workflow.b5': 'تسريع عمليات الأعمال',
    'services.workflow.b6': 'تمكين مزامنة البيانات الفورية',
    'services.workflow.f1': 'تكامل n8n',
    'services.workflow.o1': 'إدارة سير العمل',
    'services.workflow.o2': 'تكامل الأنظمة',
    'services.workflow.o3': 'تقارير وتحليلات',
    'services.workflow.o4': 'إشعارات تلقائية',
    'services.workflow.o5': 'لوحة تحكم شاملة',
    'services.workflow.o6': 'تدريب ومتابعة',
    'services.workflow.o7': 'دعم فني لمدة سنة مجاناً',
    'services.workflow.o8': '5 تغييرات مجانية خلال السنة الأولى',
    'services.workflow.f2': 'تنسيق API',
    'services.workflow.f3': 'تدفقات مدفوعة بالأحداث',
    'services.workflow.f4': 'تطوير العقد المخصصة',
    'services.workflow.f5': 'تحسين سير العمل',
    'services.workflow.f6': 'المراقبة والتحليلات',

    // Technologies
    'tech.label': 'التقنيات',
    'tech.title1': 'مجموعة',
    'tech.title2': 'تقنياتنا',
    'tech.subtitle': 'نستفيد من أحدث التقنيات والأدوات لبناء حلول قوية وقابلة للتطوير ومستقبلية.',
    'tech.cta': 'لا ترى ما تحتاجه؟ نحن نستكشف دائماً تقنيات جديدة.',
    'tech.ctaLink': '← دعنا نناقش متطلباتك',
    'tech.frontend': 'الواجهة الأمامية',
    'tech.backend': 'الخادم',
    'tech.mobile': 'الموبايل',
    'tech.cloud': 'السحابة والـ DevOps',
    'tech.automation': 'الأتمتة',
    'tech.tools': 'الأدوات',

    // Process
    'process.label': 'منهجيتنا',
    'process.title1': 'كيف',
    'process.title2': 'نعمل',
    'process.subtitle': 'منهجية مثبتة تضمن الجودة والشفافية والتسليم الناجح لكل مشروع.',
    'process.step1.title': 'الاكتشاف',
    'process.step1.desc': 'نبدأ بفهم عملك وأهدافك وتحدياتك من خلال استشارة معمقة.',
    'process.step2.title': 'البحث والتحليل',
    'process.step2.desc': 'نحلل سوقك ومنافسيك ومستخدميك لإبلاغ نهجنا الاستراتيجي.',
    'process.step3.title': 'التصميم والتخطيط',
    'process.step3.desc': 'إنشاء النماذج الأولية والمواصفات التقنية المفصلة لحلك.',
    'process.step4.title': 'التطوير',
    'process.step4.desc': 'تطوير مرن مع تحديثات منتظمة واختبار وتكرار بناءً على ملاحظاتك.',
    'process.step5.title': 'الإطلاق',
    'process.step5.desc': 'اختبار شامل وتحسين ونشر سلس لحلك.',
    'process.step6.title': 'الدعم والنمو',
    'process.step6.desc': 'صيانة مستمرة وتحديثات وإرشادات استراتيجية لمساعدة عملك على النمو.',

    // Contact
    'contact.label': 'تواصل معنا',
    'contact.title1': 'لنبني',
    'contact.title2': 'معاً',
    'contact.subtitle': 'مستعد لبدء مشروعك القادم؟ يسعدنا سماعك. تواصل معنا ولننشئ شيئاً مذهلاً.',
    'contact.form.name': 'اسمك',
    'contact.form.namePlaceholder': 'محمد أحمد',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.emailPlaceholder': 'mohamed@company.com',
    'contact.form.company': 'الشركة (اختياري)',
    'contact.form.companyPlaceholder': 'اسم شركتك',
    'contact.form.message': 'رسالتك',
    'contact.form.messagePlaceholder': 'أخبرنا عن مشروعك...',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.sending': 'جاري الإرسال...',
    'contact.info.title': 'معلومات التواصل',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.phone': 'الهاتف',
    'contact.info.location': 'الموقع',
    'contact.info.locationValue': 'فريق عن بُعد، حول العالم',
    'contact.follow': 'تابعنا',
    'contact.response': 'رد سريع مضمون',
    'contact.responseDesc': 'نرد عادة خلال 24 ساعة',
    'contact.toast.title': 'تم إرسال الرسالة!',
    'contact.toast.desc': 'سنرد عليك خلال 24 ساعة.',

    // News
    'news.label': 'آخر الأخبار',
    'news.title1': 'ابقَ على اطلاع',
    'news.title2': 'بأخبارنا',
    'news.subtitle': 'تابع رحلتنا بينما نحضر المؤتمرات ونشارك في الفعاليات ونشارك التحديثات المهمة حول شركتنا ورؤى الصناعة.',
    'news.readMore': 'اقرأ المزيد',
    'news.viewAll': 'عرض جميع الأخبار',
    'news.allNews': 'جميع الأخبار والتحديثات',
    'news.allNewsDesc': 'استكشف جميع آخر التحديثات والفعاليات والإنجازات',
    'news.category.conference': 'مؤتمر',
    'news.category.event': 'فعالية',
    'news.category.update': 'تحديث',
    'news.category.award': 'جائزة',
    'news.dateFormat': 'dd MMM yyyy',

    // Footer
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.description': 'APPLKANJI تقدم حلولاً رقمية مبتكرة وقابلة للتطوير تساعد الشركات على النمو من خلال التكنولوجيا والأتمتة والأنظمة الرقمية الذكية.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.contactInfo': 'معلومات التواصل',
    'footer.followUs': 'تابعنا',
    'footer.socialDesc': 'ابق على تواصل معنا على وسائل التواصل الاجتماعي',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.cookies': 'سياسة الكوكيز',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'ar' ? 'ar' : 'en') as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
